/****** 对象:  Database [admin_platform]    脚本日期: 11/21/2019 18:11:52 ******/
CREATE DATABASE [admin_platform]
 COLLATE Chinese_PRC_CI_AS
GO
EXEC dbo.sp_dbcmptlevel @dbname=N'admin_platform', @new_cmptlevel=100
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [admin_platform].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO
ALTER DATABASE [admin_platform] SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE [admin_platform] SET ANSI_NULLS OFF
GO
ALTER DATABASE [admin_platform] SET ANSI_PADDING OFF
GO
ALTER DATABASE [admin_platform] SET ANSI_WARNINGS OFF
GO
ALTER DATABASE [admin_platform] SET ARITHABORT OFF
GO
ALTER DATABASE [admin_platform] SET AUTO_CLOSE OFF
GO
ALTER DATABASE [admin_platform] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [admin_platform] SET AUTO_SHRINK ON
GO
ALTER DATABASE [admin_platform] SET AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE [admin_platform] SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE [admin_platform] SET CURSOR_DEFAULT  GLOBAL
GO
ALTER DATABASE [admin_platform] SET CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE [admin_platform] SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE [admin_platform] SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE [admin_platform] SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE [admin_platform] SET  DISABLE_BROKER
GO
ALTER DATABASE [admin_platform] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO
ALTER DATABASE [admin_platform] SET DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE [admin_platform] SET TRUSTWORTHY OFF
GO
ALTER DATABASE [admin_platform] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO
ALTER DATABASE [admin_platform] SET PARAMETERIZATION SIMPLE
GO
ALTER DATABASE [admin_platform] SET  READ_WRITE
GO
ALTER DATABASE [admin_platform] SET RECOVERY FULL
GO
ALTER DATABASE [admin_platform] SET  MULTI_USER
GO
ALTER DATABASE [admin_platform] SET PAGE_VERIFY CHECKSUM
GO
ALTER DATABASE [admin_platform] SET DB_CHAINING OFF