/****** 对象:  Database [AgentDB]    脚本日期: 11/21/2019 18:11:52 ******/
CREATE DATABASE [AgentDB]
 COLLATE Chinese_PRC_CI_AS
GO
EXEC dbo.sp_dbcmptlevel @dbname=N'AgentDB', @new_cmptlevel=100
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AgentDB].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO
ALTER DATABASE [AgentDB] SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE [AgentDB] SET ANSI_NULLS OFF
GO
ALTER DATABASE [AgentDB] SET ANSI_PADDING OFF
GO
ALTER DATABASE [AgentDB] SET ANSI_WARNINGS OFF
GO
ALTER DATABASE [AgentDB] SET ARITHABORT OFF
GO
ALTER DATABASE [AgentDB] SET AUTO_CLOSE OFF
GO
ALTER DATABASE [AgentDB] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [AgentDB] SET AUTO_SHRINK ON
GO
ALTER DATABASE [AgentDB] SET AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE [AgentDB] SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE [AgentDB] SET CURSOR_DEFAULT  GLOBAL
GO
ALTER DATABASE [AgentDB] SET CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE [AgentDB] SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE [AgentDB] SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE [AgentDB] SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE [AgentDB] SET  DISABLE_BROKER
GO
ALTER DATABASE [AgentDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO
ALTER DATABASE [AgentDB] SET DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE [AgentDB] SET TRUSTWORTHY OFF
GO
ALTER DATABASE [AgentDB] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO
ALTER DATABASE [AgentDB] SET PARAMETERIZATION SIMPLE
GO
ALTER DATABASE [AgentDB] SET  READ_WRITE
GO
ALTER DATABASE [AgentDB] SET RECOVERY FULL
GO
ALTER DATABASE [AgentDB] SET  MULTI_USER
GO
ALTER DATABASE [AgentDB] SET PAGE_VERIFY CHECKSUM
GO
ALTER DATABASE [AgentDB] SET DB_CHAINING OFF